'DATA_DIR': '../../generated_data_v2'
'DATA_SOURCE_DIR' : '../../generated_data_v2'
'DIR' : 'us_import1'
'OP_DIR' : 'output'
'SAVE_DIR' : 'save_dir'
'MODEL_DIR' : 'model_save_dir'
'MODEL_NAME' : 'model_mead'
'log_file' : 'MEAD_execution_log.log'
'num_jobs' : 8

'fraud_ratio' : 0.5
'anomaly_ratio' : 0.4

'us_import1':
  'learning_rate' : 0.0005
  'use_pretrained' : False
  'show_loss_figure' : False
  'save_loss_figure' : True
  'use_bias' : Falseus
  'saved_model_file' : 'frozen_model_mead16_1584989948.pb'
  'num_epochs' : 25
  'op_dims' : 16
  'batchsize': 128
  'num_neg_samples' : 15
  'test_data_size' : 40000

'us_import2':
  'learning_rate' : 0.0005
  'use_pretrained' : False
  'show_loss_figure' : False
  'save_loss_figure' : False
  'use_bias' : False
  'saved_model_file' : 'frozen_model_mead16_1585585938.pb'
  'num_epochs' : 25
  'op_dims' : 16
  'batchsize': 128
  'num_neg_samples' : 15
  'test_data_size' : 60000

'us_import3':
  'learning_rate' : 0.0005
  'use_pretrained' : False
  'show_loss_figure' : False
  'save_loss_figure' : False
  'use_bias' : False
  'saved_model_file' : 'frozen_model_mead16_1584997705.pb'
  'num_epochs' : 25
  'op_dims' : 16
  'batchsize': 128
  'num_neg_samples' : 15
  'test_data_size' : 80000