'DATA_DIR': '../../generated_data_v1'
'DIR' : 'us_import1'
'OP_DIR' : 'output'
'SAVE_DIR' : 'save_dir'
'MODEL_DIR' : 'model_save_dir'
'MODEL_NAME' : 'model_mead'
'log_file' : 'MEAD_execution_log.log'
'num_jobs' : 8

'us_import1':
  'learning_rate' : 0.0005
  'use_pretrained' : False
  'show_loss_figure' : False
  'save_loss_figure' : True
  'use_bias' : False
  'saved_model_file' : False
  'num_epochs' : 25
  'op_dims' : 16
  'batchsize': 128
  'num_neg_samples' : 15

'us_import2':
  'learning_rate' : 0.0005
  'use_pretrained' : True
  'show_loss_figure' : False
  'save_loss_figure' : False
  'use_bias' : False
  'saved_model_file' : False
  'num_epochs' : 25
  'op_dims' : 16
  'batchsize': 128
  'num_neg_samples' : 15

'us_import3':
  'learning_rate' : 0.0005
  'use_pretrained' : False
  'show_loss_figure' : False
  'save_loss_figure' : False
  'use_bias' : False
  'saved_model_file' : False
  'num_epochs' : 25
  'op_dims' : 16
  'batchsize': 128
  'num_neg_samples' : 15