'DATA_DIR': '../../generated_data'
'_DIR' : 'peru_export'
'OP_DIR' : 'output'
'SAVE_DIR' : 'save_dir'
'MODEL_NAME' : 'model_v1_2'
'log_file': 'results_log_1.log'
'china_import':
  'learning_rate' : 0.00025
  'use_pretrained' : False
  'show_loss_figure' : False
  'save_loss_figure' : False
  'use_bias' : True
  'saved_model_file' : False
  'num_epochs' : 25
  'op_dims' : 8,12
  'batchsize': 64
  'num_neg_samples' : 15
'peru_export':
  'learning_rate' : 0.00025
  'use_pretrained' : False
  'show_loss_figure' : False
  'save_loss_figure' : False
  'use_bias' : True
  'saved_model_file' : False
  'num_epochs' : 25
  'op_dims' : 8,8
  'batchsize': 64
  'num_neg_samples' : 15
'us_import':
  'learning_rate' : 0.00025
  'use_pretrained' : False
  'show_loss_figure' : False
  'save_loss_figure' : False
  'use_bias' : True
  'saved_model_file' : False
  'num_epochs' : 25
  'op_dims' : 8,12
  'batchsize': 64
  'num_neg_samples' : 15
'china_export':
  'learning_rate' : 0.00025
  'use_pretrained' : False
  'show_loss_figure' : False
  'save_loss_figure' : False
  'use_bias' : True
  'saved_model_file' : False
  'num_epochs' : 25
  'op_dims' : 8,12
  'batchsize': 64
  'num_neg_samples' : 15
