'save_dir': './../../generated_data_v1'
'DIR': 'china_export'
'cleaned_csv_subdir' : 'cleaned_csv'
'train_data_file' : 'train_data.csv'
'test_data_file_v1' : 'test_data_v1.csv'
'hscode_filter_file_loc' : './../../MetaData'
'hscode_filter_file_pattern' : '_hs_codes.txt' 
'china_import':
  'use_cols':
    - 'PanjivaRecordID'
    - 'ConsigneePanjivaID'
    - 'ShipmentOrigin'
    - 'Province'
    - 'CountryOfSale'
    - 'TransportMethod'
    - 'AdminRegion'
    - 'TradeType'
    - 'HSCode'
    
  'num_neg_samples': 15
  'column_value_filters':
    'ShipmentOrigin':
      - 'Countries (reg.) un-known'
    'CountryOfSale':
      - 'Countries (reg.) un-known'
  'num_neg_samples_ape': 3
  'low_freq_bound': 5
'china_export':
  'use_cols':
    - 'PanjivaRecordID'
    - 'AdminRegion'
    - 'CountryOfSale'
    - 'HSCode'
    - 'ShipmentDestination'
    - 'Province'
    - 'ShipperPanjivaID'
    - 'TradeType'
    - 'TransportMethod'
    - 'HSCode'
    
  'num_neg_samples': 15
  'column_value_filters': False
  'num_neg_samples_ape': 3
  'low_freq_bound': 5
  
'us_import':
  'use_cols':
    - 'PanjivaRecordID'
    - 'ConsigneePanjivaID'
    - 'ShipperPanjivaID'
    - 'ShipmentOrigin'
    - 'ShipmentDestination'
    - 'HSCode'
    - 'PortOfUnlading'
    - 'PortOfLading'
    - 'Carrier'
  'num_neg_samples_v1': 15
  'column_value_filters':
    'Carrier':
      - '(Usa))'
  'num_neg_samples_ape': 3
  'low_freq_bound': 3

