'save_dir': './../../generated_data'
'_DIR': 'peru_export'
'us_import':
  'use_cols':
    - 'PanjivaRecordID'
    - 'ConsigneePanjivaID'
    - 'ShipperCountry'
    - 'ShipperPanjivaID'
    - 'ShipmentOrigin'
    - 'ShipmentDestination'
    - 'hscode_6'
    - 'PortOfUnlading'
    - 'PortOfLading'
    - 'Carrier'
  'num_neg_samples_v1': 15
  'column_value_filters':
    'Carrier':
      - '(Usa))'
  'num_neg_samples_ape': 3
  'low_freq_bound': 5
'peru_export':
  'use_cols':
    - 'PanjivaRecordID'
    - 'ShipmentDestination'
    - 'hscode_6'
    - 'ShipperPanjivaID'
    - 'PortOfUnladingUNLOCODE'
    - 'CustomsCode'
    - 'TransportMethod'
    - 'LocationCode'
  'num_neg_samples_v1': 15
  'column_value_filters': False
  'num_neg_samples_ape': 3
  'low_freq_bound': 5
'china_import':
  'use_cols':
    - 'PanjivaRecordID'
    - 'ConsigneePanjivaID'
    - 'ShipmentOrigin'
    - 'Province'
    - 'CountryOfSale'
    - 'TransportMethod'
    - 'AdminRegion'
    - 'TradeType'
    - 'hscode_6'
  'num_neg_samples_v1': 15
  'column_value_filters':
    'ShipmentOrigin':
      - 'Countries (reg.) un-known'
    'CountryOfSale':
      - 'Countries (reg.) un-known'
  'num_neg_samples_ape': 3
  'low_freq_bound': 5
'china_export':
  'use_cols':
    - 'PanjivaRecordID'
    - 'AdminRegion'
    - 'CountryOfSale'
    - 'hscode_6'
    - 'ShipmentDestination'
    - 'Province'
    - 'ShipperPanjivaID'
    - 'ShipperStateRegion'
    - 'ShipperCountry'
    - 'TradeType'
    - 'TransportMethod'
  'num_neg_samples_v1': 15
  'column_value_filters': False
  'num_neg_samples_ape': 3
  'low_freq_bound': 5