DATA_SOURCE_DIR_1 : './../../generated_data_v1'
DATA_SOURCE_DIR_2 : './../../AD_System_output_v2'
model_use_data_DIR : 'model_use_data'
serial_mapping_df_name : 'Serial_mapping.csv'
serial_mapping_df_loc : './../GraphEmb_2/model_use_data'