'DATA_DIR': '../../generated_data'
'_DIR' : 'china_import2'
'OP_DIR' : 'output'
'SAVE_DIR' : 'save_dir'
'K' : 1
'peru_export2' :
  'log_file' : 'results_k1.log'
'china_import2' :
  'log_file' : 'results_k1.log'
'us_import' :
  'log_file' : 'results_k1.log'
'us_import2' :
  'log_file' : 'results_k2.log'
'china_export':
  'log_file': 'results_k2.log'
