'DATA_DIR': '../../generated_data_v1'
'DIR' : 'us_import1'
'OP_DIR' : 'output'
'SAVE_DIR' : 'save_dir'
'MODEL_NAME' : 'model_002'
'eval_type' : 1
'log_file' : 'main.log'
'num_jobs' : 40
'train_data_file' : 'train_data.csv'
'model_data_save_dir' : 'model_files'
'negative_samples_file' : 'negative_samples_v1.csv'
'us_import1':
  'learning_rate' : 0.0005
  'use_pretrained' : False
  'show_loss_figure' : False
  'save_loss_figure' : False
  'use_bias' : True
  'saved_model_signature' : 'model_002_1'
  'num_epochs' : 25
  'op_dims' : 12
  'batchsize': 128
  'num_neg_samples' : 15
  'Refresh_Embeddings' : False
  'entity_embedding_dims': 256
  'eEmb_num_epochs' : 5
  'c2v_num_epochs': 2
  'interaction_layer_dim' : 32
  'context_dim': 32
  'lstm_dim': 64

'china_export1':
  'learning_rate' : 0.0005
  'use_pretrained' : True
  'show_loss_figure' : False
  'save_loss_figure' : False
  'use_bias' : True
  'saved_model_file' : 'frozen_model_v1_216_1577133792.pb'
  'num_epochs' : 8
  'op_dims' : 16
  'batchsize': 256
  'num_neg_samples' : 15
  'eEmb_emb_epochs': 20
  'entity_embedding_dims' : 512
  'c2v_num_epochs' : 25

'china_import1':
  'learning_rate' : 0.0005
  'use_pretrained' : True
  'show_loss_figure' : False
  'save_loss_figure' : False
  'use_bias' : True
  'saved_model_file' : 'frozen_model_v1_212_1566001021.pb'
  'num_epochs' : 25
  'op_dims' : 12
  'batchsize': 128
  'num_neg_samples' : 15

'us_import2':
  'learning_rate' : 0.0005
  'use_pretrained' : True
  'show_loss_figure' : False
  'save_loss_figure' : False
  'use_bias' : True
  'saved_model_file' : 'frozen_model_v1_214_1566057286.pb'
  'num_epochs' : 25
  'op_dims' : 14
  'batchsize': 128
  'num_neg_samples' : 15