'save_dir': 'generated_data'
'_DIR': 'us_import2'
'us_import2':
  'use_cols':
    - 'PanjivaRecordID'
    - 'ConsigneePanjivaID'
    - 'ShipperPanjivaID'
    - 'ShipmentOrigin'
    - 'ShipmentDestination'
    - 'hscode_6'
    - 'PortOfUnlading'
    - 'PortOfLading'
    - 'Carrier'
  'num_neg_samples_v1': 10
  'column_value_filters':
    'Carrier':
      - '(Usa))'
  'low_freq_bound': 3