'DATA_DIR': '../../generated_data'
'_DIR' : 'us_import'
'OP_DIR' : 'output'
'SAVE_DIR' : 'save_dir'
'MODEL_NAME' : 'model_v1_2'
'eval_type' : 1
'log_file' : 'main.log'
'num_jobs' : 1
'china_import':
  'learning_rate' : 0.0005
  'use_pretrained' : False
  'show_loss_figure' : False
  'save_loss_figure' : False
  'use_bias' : True
  'saved_model_file' : False
  'num_epochs' : 25
  'op_dims' : 12
  'batchsize': 128
  'num_neg_samples' : 15
'peru_export':
  'learning_rate' : 0.0005
  'use_pretrained' : False
  'show_loss_figure' : False
  'save_loss_figure' : False
  'use_bias' : True
  'saved_model_file' : False
  'num_epochs' : 25
  'op_dims' : 10
  'batchsize': 128
  'num_neg_samples' : 15
'us_import':
  'learning_rate' : 0.0005
  'use_pretrained' : False
  'show_loss_figure' : False
  'save_loss_figure' : False
  'use_bias' : True
  'saved_model_file' : False
  'num_epochs' : 25
  'op_dims' : 12
  'batchsize': 128
  'num_neg_samples' : 10
'china_export':
  'learning_rate' : 0.0005
  'use_pretrained' : False
  'show_loss_figure' : False
  'save_loss_figure' : False
  'use_bias' : True
  'saved_model_file' : 'frozen_model_v1_212_1563826937.pb'
  'num_epochs' : 25
  'op_dims' : 12
  'batchsize': 128
  'num_neg_samples' : 15

