'DATA_DIR': '../../data_v1'
'_DIR' : 'data_2'
'OP_DIR' : 'output'
'SAVE_DIR' : 'save_dir'
'MODEL_NAME' : 'model_v1_2'
'eval_type' : 1
'num_jobs' : 1
'data_2':
  'learning_rate' : 0.00005
  'use_pretrained' : False
  'show_loss_figure' : False
  'save_loss_figure' : False
  'use_bias' : True
  'saved_model_file' : 'frozen_model_5_v18_6_1561940134.pb'
  'num_epochs' : 30
  'op_dims' : 8,6
  'batchsize': 2048
  'alpha' : 0.01
  'lof_K' : 20
  'w_mean' : True
  'log_file' : 'results_data_2_log.csv'
