'SOURCE_DATA_DIR_1' : './../../generated_data_v2'
'SOURCE_DATA_DIR_2' : './../../AD_system_output_v2'
'DIR': 'us_import1'
'SAVE_DATA_DIR': './saved_data/'
'id_col': 'PanjivaRecordID'
'hscode_col': 'HSCode'
'model_use_data_DIR' : 'model_use_data'
'num_jobs': 8
'random_walk_save_subdir' : 'RW_Samples'
'mp2v_data' : 'mp2v_data'
'mp2v_context_size' : 6
'RW_Samples_DIR' : 'RW_Samples'