'DATA_DIR': '../../generated_data'
'_DIR' : 'us_import'
'OP_DIR' : 'output'
'SAVE_DIR' : 'save_dir'
'MODEL_NAME' : 'model_v1_2'
'eval_type' : 1
'num_jobs' : 1
'china_import':
  'learning_rate' : 0.0005
  'use_pretrained' : False
  'show_loss_figure' : False
  'save_loss_figure' : False
  'use_bias' : True
  'saved_model_file' : 'frozen_model_v1_28_12_1562798264.pb'
  'num_epochs' : 20
  'op_dims' : 8,12
  'batchsize': 128
  'log_file' : 'results_data_2_log.csv'
  'num_neg_samples' : 15
'peru_export':
  'learning_rate' : 0.0005
  'use_pretrained' : False
  'show_loss_figure' : False
  'save_loss_figure' : False
  'use_bias' : True
  'saved_model_file' : 'frozen_model_v1_28_8_1562618642.pb'
  'num_epochs' : 25
  'op_dims' : 8,8
  'batchsize': 128
  'log_file' : 'results_data_2_log.csv'
  'num_neg_samples' : 15
'us_import':
  'learning_rate' : 0.0001
  'use_pretrained' : False
  'show_loss_figure' : False
  'save_loss_figure' : False
  'use_bias' : True
  'saved_model_file' : 'frozen_model_v1_28_12_1562789098.pb'
  'num_epochs' : 20
  'op_dims' : 8,12
  'batchsize': 64
  'log_file' : 'results_data_2_log.csv'
  'num_neg_samples' : 15

