'DATA_DIR': '../../generated_data'
'_DIR' : 'peru_export'
'OP_DIR' : 'output'
'SAVE_DIR' : 'save_dir'
'MODEL_NAME': 'model_ape'
'china_import':
  'embed_size': 10
  'num_epocs': 5
  'batch_size': 128
  'use_pretrained': True
  'learning_rate': 0.001
  'saved_model_file' : False
'peru_export':
  'embed_size': 10
  'num_epocs': 8
  'batch_size': 128
  'saved_model_file': 'model_ape_10_k_21_frozen.pb'
  'use_pretrained': False
  'learning_rate': 0.001
'us_import':
  'embed_size': 12
  'num_epocs': 12
  'batch_size': 128
  'saved_model_file' : False
  'use_pretrained': False
  'learning_rate': 0.001